"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Plus, X } from "lucide-react";
import { StatusBadge } from "@/components/dashboard/status-badge";
import type { InvoiceDTO } from "@/modules/factures/types";
import type { ClientDTO } from "@/modules/clients/types";

export default function InvoicesPage() {
  const [invoices, setInvoices] = useState<InvoiceDTO[]>([]); const [clients, setClients] = useState<ClientDTO[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ clientId: "", reference: "", amount: "", issuedAt: new Date().toISOString().slice(0, 10), dueAt: "" });
  async function load() { const [invoiceRes, clientRes] = await Promise.all([fetch("/api/v1/invoices?limit=100"), fetch("/api/v1/clients?limit=100")]); if (invoiceRes.ok) setInvoices((await invoiceRes.json()).items ?? []); if (clientRes.ok) setClients((await clientRes.json()).items ?? []); }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); const response = await fetch("/api/v1/invoices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, amount: Number(form.amount) }) }); if (!response.ok) { setError((await response.json().catch(() => ({}))).error ?? "Création impossible."); return; } setOpen(false); await load(); }
  return <div className="space-y-6 max-w-[1280px] mx-auto"><div className="flex items-center justify-between"><h1 className="text-3xl font-bold tracking-tight text-[#0F172A]">Factures</h1><button onClick={() => { setError(""); setOpen(true); }} className="inline-flex items-center gap-2 rounded-xl bg-[#4F46E5] px-4 py-2 text-xs font-semibold text-white"><Plus className="h-4 w-4" />Nouvelle facture</button></div>
    {open && <form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2"><div className="flex justify-between sm:col-span-2"><h2 className="font-semibold">Nouvelle facture</h2><button type="button" onClick={() => setOpen(false)}><X className="h-4 w-4" /></button></div><select required value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })} className="rounded-xl border p-2 text-sm"><option value="">Choisir un client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.identity.name}</option>)}</select><input required placeholder="Référence" value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} className="rounded-xl border p-2 text-sm" /><input required type="number" min="0.01" step="0.01" placeholder="Montant" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} className="rounded-xl border p-2 text-sm" /><label className="text-xs">Émission<input required type="date" value={form.issuedAt} onChange={(e) => setForm({ ...form, issuedAt: e.target.value })} className="mt-1 block w-full rounded-xl border p-2 text-sm" /></label><label className="text-xs">Échéance<input required type="date" value={form.dueAt} onChange={(e) => setForm({ ...form, dueAt: e.target.value })} className="mt-1 block w-full rounded-xl border p-2 text-sm" /></label><button className="rounded-xl bg-[#4F46E5] px-4 py-2 text-sm font-semibold text-white">Créer</button>{error && <p className="text-xs text-red-600 sm:col-span-2">{error}</p>}</form>}
    <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead><tr className="bg-[#F8FAFC] text-left text-xs text-[#64748B]"><th className="px-4 py-3">Référence</th><th>Montant</th><th>Reste dû</th><th>Échéance</th><th>Statut</th><th className="px-4">Actions</th></tr></thead><tbody className="divide-y">{invoices.map((invoice) => <tr key={invoice.id}><td className="px-4 py-3 font-semibold">{invoice.reference}</td><td>{Number(invoice.amount).toFixed(2)} €</td><td>{Number(invoice.amountRemaining).toFixed(2)} €</td><td>{new Date(invoice.dueAt).toLocaleDateString("fr-FR")}</td><td><StatusBadge status={invoice.status} /></td><td className="px-4"><Link href={`/invoices/${invoice.id}`} className="rounded-xl border px-3 py-1.5 text-xs font-semibold">Voir détail</Link></td></tr>)}</tbody></table>{!invoices.length && <p className="p-6 text-center text-sm text-[#64748B]">Aucune facture</p>}</div></div>;
}
